runtime: nodejs18

env_variables:
  NODE_ENV: "production"
  GOOGLE_CLOUD_PROJECT_ID: "artisan-social-generator"

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  max_concurrent_requests: 50

handlers:
  - url: /api/.*
    secure: always
    script: auto

  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg))$
    static_files: frontend/build/\1
    upload: frontend/build/.*\.(js|css|png|jpg|jpeg|gif|ico|svg)$
    secure: always

  - url: /.*
    static_files: frontend/build/index.html
    upload: frontend/build/index.html
    secure: always