steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'frontend'
  
  # Build React app
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'frontend'
  
  # Install backend dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'backend'
  
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml', '--quiet']
    dir: 'deploy'
  
  # Deploy Cloud Functions
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions', 'deploy', 'generateContent',
      '--gen2',
      '--runtime', 'nodejs18',
      '--trigger-http',
      '--allow-unauthenticated',
      '--region', 'us-central1',
      '--source', 'backend/functions',
      '--entry-point', 'generateContent'
    ]

timeout: '1800s'